spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo_schema
    username: demo_user
    password: pwd2024!!
mybatis:
  mapper-locations: classpath:/mybatis/mappers/**/*.xml # mapper file location
  configuration:
    map-underscore-to-camel-case: true # convert snake_case to camelCase
    default-enum-type-handler: com.example.demo.admin.global.config.define.EnumTypeHandler # define defaultEnumTypeHandler
  type-aliases-package: com.example.demo.admin.domain.*.domain # define package path in mapper file
logging:
  level:
    com.example.demo.admin.domain:
      customer.repository.mybatis: trace
      admin.repository.mybatis: trace
      login.repository.mybatis: trace
server:
  error:
    whitelabel:
      enabled: false # not use spring boot default error page
# spring.messages.basename=messages